-- public.auditoria_produtos definição

-- Drop table

-- DROP TABLE public.auditoria_produtos;

CREATE TABLE public.auditoria_produtos (
	id bigserial NOT NULL,
	produto_id int8 NOT NULL,
	data_alteracao timestamp DEFAULT now() NULL,
	preco_antigo numeric(10, 2) NULL,
	preco_novo numeric(10, 2) NULL,
	CONSTRAINT auditoria_produtos_pkey PRIMARY KEY (id)
);


-- public.clientes definição

-- Drop table

-- DROP TABLE public.clientes;

CREATE TABLE public.clientes (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	banco varchar(255) NULL,
	cnpj varchar(255) NULL,
	cond_pgto varchar(255) NULL,
	estado varchar(255) NULL,
	ie varchar(255) NULL,
	nome varchar(255) NOT NULL,
	telefone varchar(255) NULL,
	cpf varchar(14) NULL,
	CONSTRAINT clientes_pkey PRIMARY KEY (id)
);


-- public.produtos definição

-- Drop table

-- DROP TABLE public.produtos;

CREATE TABLE public.produtos (
	id bigserial NOT NULL,
	nome varchar(255) NOT NULL,
	valor_200m numeric(10, 2) NOT NULL,
	valor_15m numeric(10, 2) NOT NULL,
	embalagem varchar(255) NULL,
	entradas float8 NULL,
	estoque_inicial float8 NULL,
	preco float8 NOT NULL,
	saidas float8 NULL,
	CONSTRAINT produtos_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_produto_nome ON public.produtos USING btree (nome);

-- Table Triggers

create trigger tr_auditoria_preco before
update
    on
    public.produtos for each row execute function fn_auditoria_preco();


-- public.vendas definição

-- Drop table

-- DROP TABLE public.vendas;

CREATE TABLE public.vendas (
	id bigserial NOT NULL,
	cliente_id int8 NOT NULL,
	data_venda date DEFAULT CURRENT_DATE NOT NULL,
	valor_total numeric(10, 2) NOT NULL,
	forma_pagamento varchar(50) NOT NULL,
	status varchar(50) DEFAULT 'Concluída'::character varying NOT NULL,
	CONSTRAINT vendas_pkey PRIMARY KEY (id),
	CONSTRAINT vendas_valor_total_check CHECK ((valor_total >= (0)::numeric)),
	CONSTRAINT vendas_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clientes(id)
);


-- public.itens_venda definição

-- Drop table

-- DROP TABLE public.itens_venda;

CREATE TABLE public.itens_venda (
	id bigserial NOT NULL,
	venda_id int8 NOT NULL,
	produto_id int8 NOT NULL,
	quantidade int4 NOT NULL,
	preco_unitario numeric(10, 2) NOT NULL,
	total_item numeric(10, 2) NOT NULL,
	CONSTRAINT itens_venda_pkey PRIMARY KEY (id),
	CONSTRAINT itens_venda_quantidade_check CHECK ((quantidade > 0)),
	CONSTRAINT itens_venda_produto_id_fkey FOREIGN KEY (produto_id) REFERENCES public.produtos(id),
	CONSTRAINT itens_venda_venda_id_fkey FOREIGN KEY (venda_id) REFERENCES public.vendas(id)
);

-- Table Triggers

create trigger tr_baixa_estoque after
insert
    on
    public.itens_venda for each row execute function fn_baixa_estoque_venda();


-- public.relatorio_estoque_atual fonte

CREATE OR REPLACE VIEW public.relatorio_estoque_atual
AS SELECT id,
    nome,
    embalagem,
    estoque_inicial,
    entradas,
    saidas,
    estoque_inicial + entradas - saidas AS estoque_atual,
    (estoque_inicial + entradas - saidas) * preco AS valor_total_estoque
   FROM produtos
  ORDER BY nome;


-- public.relatorio_vendas_detalhadas fonte

CREATE OR REPLACE VIEW public.relatorio_vendas_detalhadas
AS SELECT v.id AS venda_id,
    v.data_venda,
    c.nome AS nome_cliente,
    p.nome AS nome_produto,
    iv.quantidade,
    iv.total_item,
    v.forma_pagamento
   FROM vendas v
     JOIN clientes c ON v.cliente_id = c.id
     JOIN itens_venda iv ON v.id = iv.venda_id
     JOIN produtos p ON iv.produto_id = p.id
  ORDER BY v.data_venda DESC;